=== a11exe/cinema/src/test/resources/hall.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns="http://cinema.com"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://cinema.com"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified">
    <!-- with XmlGrid.net Free Online Service http://xmlgrid.net -->
    <xs:element name="Hall">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="Row" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Row">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="Seat" />
            </xs:sequence>
            <xs:attribute name="number" type="xs:int"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="Seat">
        <xs:complexType>
            <xs:attribute name="number" type="xs:int"></xs:attribute>
            <xs:attribute name="price" type="xs:int"></xs:attribute>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== a11exe/cinema/src/main/resources/hall.xml
<?xml version="1.0" encoding="UTF-8"?>
<Hall xmlns="http://cinema.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://alllexe.com hall.xsd">
  <Row number="1">
    <Seat number="1" price="200"></Seat>
    <Seat number="2" price="200"></Seat>
    <Seat number="3" price="200"></Seat>
  </Row>
  <Row number="2">
    <Seat number="1" price="200"></Seat>
    <Seat number="2" price="200"></Seat>
    <Seat number="3" price="200"></Seat>
    <Seat number="4" price="200"></Seat>
    <Seat number="5" price="200"></Seat>
  </Row>
  <Row number="3">
    <Seat number="1" price="200"></Seat>
    <Seat number="2" price="200"></Seat>
    <Seat number="3" price="200"></Seat>
    <Seat number="4" price="200"></Seat>
    <Seat number="5" price="200"></Seat>
  </Row>
  <Row number="4">
    <Seat number="1" price="200"></Seat>
    <Seat number="2" price="200"></Seat>
    <Seat number="3" price="200"></Seat>
    <Seat number="4" price="200"></Seat>
    <Seat number="5" price="200"></Seat>
  </Row>
  <Row number="5">
    <Seat number="1" price="500"></Seat>
    <Seat number="2" price="500"></Seat>
    <Seat number="3" price="500"></Seat>
    <Seat number="4" price="500"></Seat>
    <Seat number="5" price="500"></Seat>
  </Row>
</Hall>
